### ISSUE TITLE
Dúvida sobre o framework JS

### ISSUE THREAD

**Issue by uselessdev** [icasei/teste-front-end#1]
Pode parecer meio óbvio mas decidi pergunta assim mesmo 😄 .

Precisa ser em algum desses frameworks (AngularJS, Backbone, Knockout) ou posso por exemplo usar algum outro como React?

**Comment by le17i** [comment]
@uselessdev sim, porque nós usamos (AngularJS e Backbone) nos nossos projetos :)

**Comment by uselessdev** [comment]
Ok. Obrigado 👍
